name = "tomu-mystic-worker"
main = "tomu-mystic-worker.js"
compatibility_date = "2024-01-01"
no_bundle = true
account_id = "b6815ad2ee3097cc0f9e79b8536776b9"

[[kv_namespaces]]
binding = "MYSTIC_SUBSCRIPTIONS"
id = "5e1c00cba16d46119b2123dc4dd23322"

[triggers]
crons = ["0 * * * *"]

[[queues.producers]]
queue = "mystic-mail-queue"
binding = "MAIL_QUEUE"

[[queues.consumers]]
queue = "mystic-mail-queue"
max_batch_size = 10
max_batch_timeout = 30
